openapi: "3.0.0"
info:
  version: 1.0.0
  title: Inventory Service
servers:
  - url: http://localhost:8080
paths:
  /inventory:
    post:
      summary: Ajouter un objet dans l'inventaire d'un héros
      operationId: ajouterObjetInventaire
      tags:
        - Inventory
      responses:
        '201':
          description: L'object a bien été ajouté à l'inventaire
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InventoryItem"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InventoryItem"
        description: Objet à ajouter à l'inventaire (ainsi que sa quantité)
    put:
      summary: Mettre à jour la quantité d'un objet dans l'inventaire d'un héros
      operationId: majObjetInventaire
      tags:
        - inventory
      responses:
        '200':
          description: L'inventaire a été mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryItem'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InventoryItem"
        description: L'objet à mettre à jour et sa quantité
    delete:
      summary: Supprimer un objet de l'inventaire d'un joueur
      operationId: supprimerObjetInventaire
      tags:
        - Inventory
      parameters:
        - name: hero
          in: query
          required: true
          description: L'id du héros
          schema:
            type: number
        - name: item
          in: query
          required: true
          description: L'id de l'objet à supprimer
          schema:
            type: number
      responses:
        '200':
          description: L'objet a bien été supprimé de l'inventaire
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InventoryItem"
  /inventory/{id_user}:
    get:
      summary: Récupérer l'inventaire d'un héro
      operationId: rechercherInventaire
      tags:
        - Inventory
      parameters:
        - name: id_hero
          in: path
          required: true
          description: L'id du héros dont on recherche l'inventaire
          schema:
            type: number
      responses:
        '200':
          description: L'inventaire a été trouvé
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/InventoryItem"
  /item/{id}:
    get:
      summary: Récupérer un objet grâce à son id
      operationId: rechercherObjet
      tags:
        - Item
      parameters:
        - name: id
          in: path
          required: true
          description: L'id de l'objet
          schema:
            type: number
      responses:
        '200':
          description: L'objet a bien été trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
components:
  schemas:
    InventoryItem:
      required:
        - id_hero
        - id_item
        - amount
      properties:
        id_hero:
          type: number
        id_item:
          type: number
        amount:
          type: number
    Item:
      required:
        - id
        - name
        - usable
        - quantity
        - unit
      properties:
        id:
          type: number
        name:
          type: string
        usable:
          type: boolean
        quantity:
          type: number
        unit:
          type: string


